version: "3.0"
services:
  web:
    image: account
    restart: always
    ports:
      - "8087:8080"

  db:
    image: mysql:5.6
    restart: always
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_database
    ports:
      - 3308:3306
